baseURL = 'https://clallam.lgbt'
languageCode = 'en-us'
title = 'Clallam|LGBTQIA2S+'
theme = 'cloudstrap'
copyright = 'A Girl Named Blaze™. All rights reserved.'

[author]
  name = 'Cloud Huxley'

[menu]
[[menu.main]]
  name = 'Home'
  pre = "<i class='fa fa-heart'></i>"
  url = '/'
  weight = -110
[[menu.main]]
  name = 'About'
  pre = "<i class='fa fa-road'></i>"
  url = '/about'
  weight = -100
[[menu.main]]
  name = 'Social'
  pre = "<i class='fas fa-people-arrows'></i>"
  url = 'https://social.clallam.lgbt/'
  weight = -90
